export const defaultColleges = [
  {
    id: "nm1",
    name: "SIES Graduate School of Technology",
    lat: 19.0435,
    lon: 73.0203,
    address: "Nerul, Navi Mumbai",
    programs: "B.E (Computer, IT, EXTC, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs, Hostel, WiFi, Placement Cell"
  },
  {
    id: "nm2",
    name: "Terna Engineering College",
    lat: 19.0330,
    lon: 73.0185,
    address: "Nerul, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "80-92%",
    medium: "English",
    facilities: "Library, Labs, Hostel, Sports, Placement Cell"
  },
  {
    id: "nm3",
    name: "Bharati Vidyapeeth College of Engineering",
    lat: 19.0438,
    lon: 73.0295,
    address: "CBD Belapur, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs, Hostel, WiFi, Placement Cell"
  },
  {
    id: "nm4",
    name: "Fr. Conceicao Rodrigues Institute of Technology (CRIT)",
    lat: 19.0335,
    lon: 73.0142,
    address: "Vashi, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical, Electronics)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "90-98%",
    medium: "English",
    facilities: "Library, Labs, Hostel, WiFi, Placement Cell"
  },
  {
    id: "nm5",
    name: "Agnel Polytechnic (Fr. Agnel Technical Complex)",
    lat: 19.0332,
    lon: 73.0139,
    address: "Vashi, Navi Mumbai",
    programs: "Diploma Engineering",
    eligibility: "10th Pass",
    cut_off: "75-90%",
    medium: "English",
    facilities: "Labs, Workshop, Library"
  },
  {
    id: "nm6",
    name: "Datta Meghe College of Engineering",
    lat: 19.2150,
    lon: 73.0850,
    address: "Airoli, Navi Mumbai",
    programs: "B.E (Computer, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm7",
    name: "Lokmanya Tilak College of Engineering",
    lat: 19.0430,
    lon: 73.0250,
    address: "Koparkhairane, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "75-90%",
    medium: "English",
    facilities: "Library, Labs, WiFi"
  },
  {
    id: "nm8",
    name: "MGM College of Engineering & Technology",
    lat: 18.9890,
    lon: 73.1270,
    address: "Kamothe, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm9",
    name: "Pillai College of Engineering",
    lat: 18.9905,
    lon: 73.1275,
    address: "New Panvel, Navi Mumbai",
    programs: "B.E (Computer, IT, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "80-95%",
    medium: "English",
    facilities: "Library, Labs, Hostel, WiFi, Placement Cell"
  },
  {
    id: "nm10",
    name: "Pillai HOC College of Engineering",
    lat: 18.9180,
    lon: 73.1670,
    address: "Rasayani, Navi Mumbai",
    programs: "B.E (Computer, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },

  {
    id: "nm11",
    name: "Ramrao Adik Institute of Technology",
    lat: 19.0445,
    lon: 73.0208,
    address: "Nerul, Navi Mumbai",
    programs: "B.E (Computer, IT, Electronics)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "90-98%",
    medium: "English",
    facilities: "Library, Labs, WiFi, Placement Cell"
  },
  {
    id: "nm12",
    name: "Saraswati College of Engineering",
    lat: 18.9900,
    lon: 73.1150,
    address: "Kharghar, Navi Mumbai",
    programs: "B.E (Computer, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm13",
    name: "ITM School of Engineering",
    lat: 18.9895,
    lon: 73.1265,
    address: "Kharghar, Navi Mumbai",
    programs: "B.Tech",
    eligibility: "12th + Entrance",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm14",
    name: "NMIMS Mukesh Patel School of Technology Management",
    lat: 18.9898,
    lon: 73.1272,
    address: "Kharghar, Navi Mumbai",
    programs: "B.Tech",
    eligibility: "NMIMS Entrance",
    cut_off: "High",
    medium: "English",
    facilities: "Library, Labs, Hostel, Placement Cell"
  },
  {
    id: "nm15",
    name: "DY Patil College of Engineering (Navi Mumbai)",
    lat: 19.0410,
    lon: 73.0190,
    address: "Nerul, Navi Mumbai",
    programs: "B.E (Computer, Mechanical, Civil)",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "75-90%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },

  {
    id: "nm16",
    name: "Vishwaniketan Institute of Management Entrepreneurship & Engineering Technology",
    lat: 18.8950,
    lon: 73.1200,
    address: "Khalapur (near Panvel)",
    programs: "B.E",
    eligibility: "12th + MHT-CET/JEE",
    cut_off: "65-80%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm17",
    name: "CKT College of Engineering",
    lat: 18.9880,
    lon: 73.1120,
    address: "Panvel",
    programs: "B.E",
    eligibility: "12th + MHT-CET",
    cut_off: "65-80%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm18",
    name: "St. John College of Engineering",
    lat: 19.4200,
    lon: 72.9100,
    address: "Palghar (nearby region)",
    programs: "B.E",
    eligibility: "12th + MHT-CET",
    cut_off: "65-80%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm19",
    name: "Universal College of Engineering",
    lat: 19.3800,
    lon: 72.8300,
    address: "Vasai (nearby)",
    programs: "B.E",
    eligibility: "12th + MHT-CET",
    cut_off: "65-80%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm20",
    name: "Shah & Anchor Kutchhi Engineering College",
    lat: 19.0600,
    lon: 72.9000,
    address: "Chembur (near Navi Mumbai)",
    programs: "B.E",
    eligibility: "12th + MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },

  {
    id: "nm21",
    name: "KJ Somaiya College of Engineering",
    lat: 19.0460,
    lon: 72.8710,
    address: "Vidyavihar (nearby)",
    programs: "B.Tech",
    eligibility: "12th + Entrance",
    cut_off: "90-99%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm22",
    name: "VJTI Mumbai",
    lat: 19.0220,
    lon: 72.8560,
    address: "Matunga (nearby)",
    programs: "B.Tech",
    eligibility: "MHT-CET",
    cut_off: "95-99%",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm23",
    name: "SPIT Mumbai",
    lat: 19.1240,
    lon: 72.8360,
    address: "Andheri (nearby)",
    programs: "B.Tech",
    eligibility: "MHT-CET",
    cut_off: "95-99%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm24",
    name: "Thadomal Shahani Engineering College",
    lat: 19.0450,
    lon: 72.8360,
    address: "Bandra (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "90-98%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm25",
    name: "Rajiv Gandhi Institute of Technology",
    lat: 19.2000,
    lon: 72.8500,
    address: "Andheri (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },

  {
    id: "nm26",
    name: "Atharva College of Engineering",
    lat: 19.1800,
    lon: 72.8400,
    address: "Malad (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "80-90%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm27",
    name: "Don Bosco Institute of Technology",
    lat: 19.0500,
    lon: 72.8300,
    address: "Kurla (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm28",
    name: "Xavier Institute of Engineering",
    lat: 19.0700,
    lon: 72.8800,
    address: "Mahim (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm29",
    name: "Vivekanand Education Society Institute of Technology",
    lat: 19.0500,
    lon: 72.8900,
    address: "Chembur (nearby)",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "90-98%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm30",
    name: "Datta Meghe Institute of Engineering Technology",
    lat: 19.2100,
    lon: 73.0900,
    address: "Airoli",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs"
  },

  {
    id: "nm31",
    name: "Smt. Indira Gandhi College of Engineering",
    lat: 19.0700,
    lon: 72.9200,
    address: "Ghansoli",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm32",
    name: "Anjuman-I-Islam Kalsekar Technical Campus",
    lat: 19.0300,
    lon: 73.0300,
    address: "Panvel",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "70-85%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm33",
    name: "MCT Rajiv Gandhi Institute of Technology",
    lat: 19.2000,
    lon: 72.8600,
    address: "Andheri",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm34",
    name: "Watumull Institute of Electronics Engineering",
    lat: 19.0700,
    lon: 72.8700,
    address: "Worli",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm35",
    name: "St. Francis Institute of Technology",
    lat: 19.2000,
    lon: 72.8400,
    address: "Borivali",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs"
  },

  {
    id: "nm36",
    name: "Vidyalankar Institute of Technology",
    lat: 19.0300,
    lon: 72.8600,
    address: "Wadala",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "90-98%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm37",
    name: "KJ Somaiya Institute of Engineering",
    lat: 19.0450,
    lon: 72.8700,
    address: "Vidyavihar",
    programs: "B.Tech",
    eligibility: "Entrance",
    cut_off: "90-99%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm38",
    name: "NMIMS Engineering School",
    lat: 18.9900,
    lon: 73.1270,
    address: "Kharghar",
    programs: "B.Tech",
    eligibility: "Entrance",
    cut_off: "High",
    medium: "English",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "nm39",
    name: "Pillai Institute of Information Technology",
    lat: 18.9908,
    lon: 73.1278,
    address: "Panvel",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "75-90%",
    medium: "English",
    facilities: "Library, Labs"
  },
  {
    id: "nm40",
    name: "SIES School of Engineering",
    lat: 19.0440,
    lon: 73.0210,
    address: "Nerul",
    programs: "B.E",
    eligibility: "MHT-CET",
    cut_off: "85-95%",
    medium: "English",
    facilities: "Library, Labs, Placement Cell"
  }
];